Refactor testing script, and now test must be passed first before analysis can be done

diff --git a/analysis/run b/analysis/run
--- a/analysis/run
+++ b/analysis/run
@@ -1,6 +1,14 @@
 #!/bin/bash
 source activate my_env # Launch into Anaconda session, because some libraries are only available in Anaconda
+
+
+# Run test
 ./test
+
+# If some test fail , exit with error
+if [ $? -ne 0 ]; then
+    exit 1
+fi
 
 cd './_1_process_raw_data'
 ./run
diff --git a/analysis/test b/analysis/test
--- a/analysis/test
+++ b/analysis/test
@@ -1,21 +1,20 @@
 #!/bin/bash
-cd './tests'
-pytest -vvdic[key]['name_cn']
-cd ..
+function check_error {
+    if [ $? -ne 0 ]; then
+        echo "Please fix this failing test first."
+        exit 1
+    fi
+}
 
-cd './_1_process_raw_data'
-./test
-cd ..
+function run_test_at {
+    cd $1
+    pytest -vv
+    check_error
+    cd ..
+}
 
-cd './_2_remove_unrelated_data'
-./test
-cd ..
-
-cd './_3_label_semantic'
-./test
-cd ..
-
-cd './_4_classification'
-./test
-
-cd ..
+run_test_at './tests'
+run_test_at './_1_process_raw_data'
+run_test_at './_2_remove_unrelated_data'
+run_test_at './_3_label_semantic'
+run_test_at './_4_classification'
